/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package greeter

import io.javalin.Javalin

fun main() {
    val app = Javalin.create().start(8000)

    with(app) {
        get("/") { ctx ->
            ctx.result("Hello world")
        }
    }
}
